BaseURL = "https://samsonchen1989.github.io/"
LanguageCode = "zh-CN"
HasCJKLanguage = true
Title = "Gamer Cat"
Theme = "hugo-pacman-theme"
pygmentsStyle = "default"
pygmentsUseClasses = true
RSSUri = "feed.xml"

[Author]
  Name = "samsonchen"

[Params]
  AuthorHomepage = "https://samsonchen1989.github.io/"
  BottomIntroduce = "Samsonchenï¼šæ— è¯ç¨‹åºå‘˜ï¼Œæ¸¸æˆçˆ±å¥½è€…ï¼Œpsnå¥–æ¯å’¸é±¼ <br/> å¯¹AIï¼ŒShaderå’ŒProcedural Content Generationæ¯”è¾ƒæ„Ÿå…´è¶£"
  Description = "hehe"
  Subtitle = "å¶å°”ç å­—å’Œå†™ä»£ç ï¼Œå¤§éƒ¨åˆ†æ—¶é—´éƒ½åœ¨ç¡è§‰ğŸ˜ªå’Œç©PS4çš„æ‡’çŒ«"
  Weibo = "canselwicecs"
  #WeiboID = 1816308191
  Twitter = "samsonchen_1989"
  GitHub = "samsonchen1989"
  #Facebook = "coderzh"
  #LinkIn = "samsonchen"
  Imglogo = "img/logo.svg"
  AuthorImg = "img/head.jpeg"
  DateFormat = "2006å¹´01æœˆ02æ—¥"
  MonthFormat = "2006å¹´01æœˆ"
  FancyBox = true

  #[Params.DuoShuo]
    #ShortName = "coderzh"

  [Params.Disqus]
    #ShortName = "samsonchen"

  [Params.GoogleAnalytics]
    #ID = ""

  [Params.Strings]
    Search = "æœç´¢"
    PageNotFound = "ä½ è®¿é—®çš„é¡µé¢ä¸å­˜åœ¨"
    ShowSideBar = "æ˜¾ç¤ºä¾§è¾¹æ "
    HideSideBar = "éšè—ä¾§è¾¹æ "
    Categories = "åˆ†ç±»"
    Archive = "å½’æ¡£"
    Tags = "æ ‡ç­¾"
    TagCloud = "æ ‡ç­¾äº‘"
    Rss = "RSS è®¢é˜…"
    TableOfContents = "æ–‡ç« ç›®å½•"

[Menu]
  [[Menu.Main]]
    Name = "é¦–é¡µ"
    URL = "/"
    Weight = 1
  [[Menu.Main]]
    Name = "å…³äº"
    URL = "/about"
    Weight = 2
